//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInformationSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountCheckList
    {
        public int Id { get; set; }
        public bool IsPersonalInfoProvided { get; set; }
        public bool IsDocumentsUploaded { get; set; }
        public bool IsPictureUploaded { get; set; }
        public Nullable<int> AccountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
