//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInformationSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int Id { get; set; }
        public string DocumentPath { get; set; }
        public string DocumentType { get; set; }
        public string FileName { get; set; }
        public System.DateTime UploadDate { get; set; }
        public int EmployeeInfoId { get; set; }
    
        public virtual EmployeeInfo EmployeeInfo { get; set; }
    }
}
