//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInformationSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyMember
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FamilyMember()
        {
            this.MedicalCheckouts = new HashSet<MedicalCheckout>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string CNIC { get; set; }
        public string Relation { get; set; }
        public int EmployeeInfoId { get; set; }
    
        public virtual EmployeeInfo EmployeeInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalCheckout> MedicalCheckouts { get; set; }
    }
}
