//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInformationSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        public int Id { get; set; }
        public System.DateTime RequestDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string LeaveType { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public bool IsCreatedByAdmin { get; set; }
        public Nullable<System.DateTime> RequestProcessDate { get; set; }
        public Nullable<int> RequestProcessByAccountId { get; set; }
        public int EmployeeInfoId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual EmployeeInfo EmployeeInfo { get; set; }
    }
}
