//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeInformationSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaySlip
    {
        public int Id { get; set; }
        public int NumberOfDaysWorked { get; set; }
        public decimal TotalSalary { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<decimal> HouseRent { get; set; }
        public Nullable<decimal> MedicalAllowance { get; set; }
        public Nullable<decimal> IncomTax { get; set; }
        public Nullable<decimal> LoanDeduction { get; set; }
        public Nullable<decimal> OtherDeductions { get; set; }
        public System.DateTime SalaryDate { get; set; }
        public int EmployeeInfoId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedByAccountId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedByAccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual EmployeeInfo EmployeeInfo { get; set; }
    }
}
